version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./src
    ports:
      - 3000:3000
    links:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
